services:
  app:
    build:
      context: .
      args:
        BUILD_ENV: dev
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app

  db:
    image: mcs07/postgres-rdkit
    environment:
      - PYTHONPATH=/app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=chemstructdb

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d chemstructdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2

  worker:
    build:
      context: .
      args:
        BUILD_ENV: dev
    entrypoint: ["rq", "worker", "-u", "redis://redis:6379"]
    depends_on:
      - redis
      - db
    volumes:
      - .:/app

