line-length = 88
indent-width = 2

[format]
indent-style = "space"
quote-style = "double"

[lint]
select = ["E", "F", "W", "I"]

[lint.per-file-ignores]
"alembic/env.py" = ["E402"]

[lint.isort]
force-single-line = true

