"""Add mol column to molecules table

Revision ID: 3e019f076fda
Revises: 4d46842d7666
Create Date: 2025-10-08 12:24:31.903462

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "3e019f076fda"
down_revision: Union[str, Sequence[str], None] = "4d46842d7666"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  pass
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  pass
  # ### end Alembic commands ###
